[package]
name = "game-off-2022"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.9"
bevy_asset_loader = "0.14.1"
bevy_pathmesh = { git = "https://github.com/vleue/bevy_pathmesh", version = "0.3.0" }
polyanya = "0.2.0"
